using System.Runtime.InteropServices;
using System.IO;
using System.Collections.Concurrent;
using FmStereoModulator.Dsp;
using NAudio.Wave;
using NAudio.Wave.SampleProviders;
namespace FmStereoModulator.Audio;
public interface IAudioSource:IDisposable { void Start(int rate); void Read(float[] stereo,int frames,CancellationToken ct); }
public interface IAudioSink:IDisposable { void Start(int rate); void Write(short[] mono,CancellationToken ct); }
public sealed class HackRfSink(double frequencyMhz, uint txGain, bool amplifierOn, bool carrierOnly=false):IAudioSink
{
    const int IqRate=2_400_000,IqOffset=0;const double PhaseScale=4294967296.0/IqRate,InputStep=(double)MpxEngine.SampleRate/IqRate;static readonly sbyte[] SinLut=BuildLut(false),CosLut=BuildLut(true);readonly BlockingCollection<byte[]> queue=new(16);readonly object startLock=new();IntPtr device;TxCallback? callback;bool initialized,started;byte[]? currentIq;byte[] carrierBuffer=[],holdBuffer=[];int currentOffset;byte lastI=110,lastQ=0;uint phaseAccumulator;long inputBase;double nextInputPosition;short previousMpx;
    public void Start(int inputRate)
    {
        try { Check(hackrf_init(),"initialization");initialized=true;Check(hackrf_open(out device),"device open");Check(hackrf_set_freq(device,(ulong)(frequencyMhz*1_000_000-IqOffset)),"frequency setup");Check(hackrf_set_sample_rate_manual(device,IqRate,1),"sample-rate setup");Check(hackrf_set_baseband_filter_bandwidth(device,1_750_000),"baseband filter setup");Check(hackrf_set_txvga_gain(device,Math.Min(txGain,47)),"TX gain setup");
            Check(hackrf_set_amp_enable(device,amplifierOn?(byte)1:(byte)0),"RF amplifier setup");callback=OnTransfer;if(carrierOnly)StartTx();
        } catch(DllNotFoundException){throw new InvalidOperationException("hackrf.dll was not found. Install the WinUSB device driver and reinstall WolfRadio.");}
    }
    public void Write(short[] mono,CancellationToken ct)
    {
        long end=inputBase+mono.Length-1;int samples=nextInputPosition<end?(int)Math.Ceiling((end-nextInputPosition)/InputStep):0;var iq=new byte[samples*2];for(int j=0;j<samples;j++){long a=(long)Math.Floor(nextInputPosition),b=a+1;double q=nextInputPosition-a;short sa=a<inputBase?previousMpx:mono[(int)(a-inputBase)],sb=mono[(int)(b-inputBase)];double f=sa+(sb-sa)*q;phaseAccumulator+=unchecked((uint)((IqOffset+75_000*(f/32768.0))*PhaseScale));int ix=(int)(phaseAccumulator>>16),k=j*2;iq[k]=unchecked((byte)CosLut[ix]);iq[k+1]=unchecked((byte)SinLut[ix]);nextInputPosition+=InputStep;}previousMpx=mono[^1];inputBase+=mono.Length;queue.Add(iq,ct);if(!started&&queue.Count>=8)StartTx();
    }
    void StartTx(){lock(startLock){if(started)return;Check(hackrf_start_tx(device,callback!,IntPtr.Zero),"TX start");started=true;}}
    static sbyte[] BuildLut(bool cosine){var x=new sbyte[65536];for(int i=0;i<x.Length;i++)x[i]=(sbyte)Math.Round((cosine?Math.Cos(2*Math.PI*i/x.Length):Math.Sin(2*Math.PI*i/x.Length))*110);return x;}
    int OnTransfer(ref Transfer t){if(carrierOnly){if(carrierBuffer.Length<t.valid_length)carrierBuffer=new byte[t.valid_length];uint step=unchecked((uint)(IqOffset*PhaseScale));for(int i=0;i+1<t.valid_length;i+=2){phaseAccumulator+=step;int ix=(int)(phaseAccumulator>>16);carrierBuffer[i]=unchecked((byte)CosLut[ix]);carrierBuffer[i+1]=unchecked((byte)SinLut[ix]);}Marshal.Copy(carrierBuffer,0,t.buffer,t.valid_length);return 0;}int written=0;while(written<t.valid_length){if(currentIq==null||currentOffset>=currentIq.Length){if(!queue.TryTake(out currentIq,50)){int missing=t.valid_length-written;if(holdBuffer.Length<missing)holdBuffer=new byte[missing];for(int i=0;i+1<missing;i+=2){holdBuffer[i]=lastI;holdBuffer[i+1]=lastQ;}Marshal.Copy(holdBuffer,0,t.buffer+written,missing);break;}currentOffset=0;}int n=Math.Min(currentIq.Length-currentOffset,t.valid_length-written);Marshal.Copy(currentIq,currentOffset,t.buffer+written,n);if(n>=2){int q=currentOffset+n-2;lastI=currentIq[q];lastQ=currentIq[q+1];}currentOffset+=n;written+=n;}return 0;}
    public void Dispose(){queue.CompleteAdding();if(started)hackrf_stop_tx(device);if(device!=IntPtr.Zero)hackrf_close(device);if(initialized)hackrf_exit();started=initialized=false;device=IntPtr.Zero;}
    static void Check(int code,string step){if(code!=0)throw new InvalidOperationException($"HackRF error during {step} (code {code}). Check the USB connection and WinUSB driver.");}
    [StructLayout(LayoutKind.Sequential)]struct Transfer{public IntPtr device,buffer;public int buffer_length,valid_length;public IntPtr rx_ctx,tx_ctx;} [UnmanagedFunctionPointer(CallingConvention.Cdecl)]delegate int TxCallback(ref Transfer transfer);
    [DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_init();[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_exit();[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_open(out IntPtr d);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_close(IntPtr d);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_set_freq(IntPtr d,ulong hz);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_set_sample_rate_manual(IntPtr d,uint hz,uint divider);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_set_baseband_filter_bandwidth(IntPtr d,uint hz);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_set_txvga_gain(IntPtr d,uint gain);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_set_amp_enable(IntPtr d,byte enable);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_start_tx(IntPtr d,TxCallback cb,IntPtr ctx);[DllImport("hackrf",CallingConvention=CallingConvention.Cdecl)]static extern int hackrf_stop_tx(IntPtr d);
}
public sealed class TestToneSource:IAudioSource { int rate; long n; public void Start(int r)=>rate=r; public void Read(float[] b,int frames,CancellationToken ct){for(int i=0;i<frames;i++){b[2*i]=(float)(.55*Math.Sin(2*Math.PI*1000*n/rate));b[2*i+1]=(float)(.35*Math.Sin(2*Math.PI*1300*n/rate));n++;}} public void Dispose(){} }
public sealed class FileAudioSource(string path):IAudioSource
{
    WaveStream? reader;ISampleProvider? samples;int rate;
    public void Start(int outputRate){rate=outputRate;Open();}
    void Open(){reader?.Dispose();reader=CreateReader(path);ISampleProvider p=reader.ToSampleProvider();if(p.WaveFormat.Channels==1)p=new MonoToStereoSampleProvider(p);else if(p.WaveFormat.Channels>2){var mux=new MultiplexingSampleProvider([p],2);mux.ConnectInputToOutput(0,0);mux.ConnectInputToOutput(1,1);p=mux;}samples=p.WaveFormat.SampleRate==rate?p:new WdlResamplingSampleProvider(p,rate);}
    static WaveStream CreateReader(string file){string ext=Path.GetExtension(file).ToLowerInvariant();return ext is ".wav" or ".mp3" or ".aif" or ".aiff"?new AudioFileReader(file):new MediaFoundationReader(file);}
    public void Read(float[] stereo,int frames,CancellationToken ct){int needed=frames*2,done=0;while(done<needed){ct.ThrowIfCancellationRequested();int n=samples!.Read(stereo,done,needed-done);if(n==0){Open();continue;}done+=n;}}
    public void Dispose(){reader?.Dispose();reader=null;samples=null;}
}
public sealed class WaveFileSink(string path):IAudioSink { FileStream? f; int bytes; public void Start(int rate){f=File.Create(path);f.Write(new byte[44]);} public void Write(short[] b,CancellationToken ct){var x=MemoryMarshal.AsBytes(b.AsSpan());f!.Write(x);bytes+=x.Length;} public void Dispose(){if(f==null)return;f.Position=0;using var w=new BinaryWriter(f,System.Text.Encoding.ASCII,true);w.Write("RIFF"u8);w.Write(36+bytes);w.Write("WAVEfmt "u8);w.Write(16);w.Write((short)1);w.Write((short)1);w.Write(192000);w.Write(384000);w.Write((short)2);w.Write((short)16);w.Write("data"u8);w.Write(bytes);f.Dispose();f=null;} }

public sealed class WaveOutSink:IAudioSink
{
    IntPtr h; readonly List<(IntPtr mem,IntPtr hdr)> pending=[];
    public void Start(int rate){var fmt=new WAVEFORMATEX{wFormatTag=1,nChannels=1,nSamplesPerSec=(uint)rate,wBitsPerSample=16,nBlockAlign=2,nAvgBytesPerSec=(uint)(rate*2),cbSize=0};Check(waveOutOpen(out h,-1,ref fmt,IntPtr.Zero,IntPtr.Zero,0));}
    public void Write(short[] b,CancellationToken ct){Reap(false);while(pending.Count>=8){ct.ThrowIfCancellationRequested();Thread.Sleep(2);Reap(false);} int size=b.Length*2;var mem=Marshal.AllocHGlobal(size);Marshal.Copy(b,0,mem,b.Length);var wh=new WAVEHDR{lpData=mem,dwBufferLength=(uint)size};var hp=Marshal.AllocHGlobal(Marshal.SizeOf<WAVEHDR>());Marshal.StructureToPtr(wh,hp,false);Check(waveOutPrepareHeader(h,hp,(uint)Marshal.SizeOf<WAVEHDR>()));Check(waveOutWrite(h,hp,(uint)Marshal.SizeOf<WAVEHDR>()));pending.Add((mem,hp));}
    void Reap(bool all){for(int i=pending.Count-1;i>=0;i--){var x=Marshal.PtrToStructure<WAVEHDR>(pending[i].hdr);if(all||(x.dwFlags&1)!=0){waveOutUnprepareHeader(h,pending[i].hdr,(uint)Marshal.SizeOf<WAVEHDR>());Marshal.FreeHGlobal(pending[i].mem);Marshal.FreeHGlobal(pending[i].hdr);pending.RemoveAt(i);}}}
    public void Dispose(){if(h==IntPtr.Zero)return;waveOutReset(h);Reap(true);waveOutClose(h);h=IntPtr.Zero;} static void Check(uint x){if(x!=0)throw new InvalidOperationException($"Errore audio Windows: {x}");}
    [StructLayout(LayoutKind.Sequential)] struct WAVEFORMATEX { public ushort wFormatTag,nChannels;public uint nSamplesPerSec,nAvgBytesPerSec;public ushort nBlockAlign,wBitsPerSample,cbSize; }
    [StructLayout(LayoutKind.Sequential)] struct WAVEHDR { public IntPtr lpData;public uint dwBufferLength,dwBytesRecorded;public IntPtr dwUser;public uint dwFlags,dwLoops;public IntPtr lpNext,reserved; }
    [DllImport("winmm.dll")]static extern uint waveOutOpen(out IntPtr h,int id,ref WAVEFORMATEX f,IntPtr cb,IntPtr inst,uint flags);[DllImport("winmm.dll")]static extern uint waveOutPrepareHeader(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveOutWrite(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveOutUnprepareHeader(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveOutReset(IntPtr h);[DllImport("winmm.dll")]static extern uint waveOutClose(IntPtr h);
}

public record AudioInputDevice(int Id,string Name){public override string ToString()=>Name;}
public sealed class WaveInSource(int deviceId=-1):IAudioSource
{
    const int CaptureRate=48000; IntPtr h,mem,hdr; int captureFrames,outputRate;
    public static IReadOnlyList<AudioInputDevice> EnumerateDevices(){var list=new List<AudioInputDevice>();uint n=waveInGetNumDevs();for(uint i=0;i<n;i++){if(waveInGetDevCaps((UIntPtr)i,out var c,(uint)Marshal.SizeOf<Caps>())==0)list.Add(new((int)i,c.name));}return list;}
    public void Start(int rate){outputRate=rate;captureFrames=Math.Max(1,rate/100*CaptureRate/rate);var f=new Fmt{tag=1,ch=2,rate=CaptureRate,avg=CaptureRate*4,align=4,bits=16};Check(waveInOpen(out h,deviceId,ref f,IntPtr.Zero,IntPtr.Zero,0));mem=Marshal.AllocHGlobal(captureFrames*4);hdr=Marshal.AllocHGlobal(Marshal.SizeOf<Hdr>());Queue();Check(waveInStart(h));}
    void Queue(){Marshal.StructureToPtr(new Hdr{data=mem,len=(uint)(captureFrames*4)},hdr,false);Check(waveInPrepareHeader(h,hdr,(uint)Marshal.SizeOf<Hdr>()));Check(waveInAddBuffer(h,hdr,(uint)Marshal.SizeOf<Hdr>()));}
    public void Read(float[] b,int count,CancellationToken ct){while((Marshal.PtrToStructure<Hdr>(hdr).flags&1)==0){ct.ThrowIfCancellationRequested();Thread.Sleep(1);}var s=new short[captureFrames*2];Marshal.Copy(mem,s,0,s.Length);for(int i=0;i<count;i++){double p=i*(captureFrames-1.0)/Math.Max(1,count-1);int a=(int)p,z=Math.Min(a+1,captureFrames-1);double q=p-a;b[i*2]=(float)((s[a*2]+(s[z*2]-s[a*2])*q)/32768.0);b[i*2+1]=(float)((s[a*2+1]+(s[z*2+1]-s[a*2+1])*q)/32768.0);}waveInUnprepareHeader(h,hdr,(uint)Marshal.SizeOf<Hdr>());Queue();}
    public void Dispose(){if(h==IntPtr.Zero)return;waveInReset(h);waveInUnprepareHeader(h,hdr,(uint)Marshal.SizeOf<Hdr>());waveInClose(h);Marshal.FreeHGlobal(mem);Marshal.FreeHGlobal(hdr);h=IntPtr.Zero;} static void Check(uint x){if(x!=0)throw new InvalidOperationException($"Errore ingresso Windows: {x}");}
    [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Auto)]struct Caps{public ushort mid,pid;public uint version;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string name;public uint formats;public ushort channels,reserved;} [StructLayout(LayoutKind.Sequential)]struct Fmt{public ushort tag,ch;public uint rate,avg;public ushort align,bits,extra;} [StructLayout(LayoutKind.Sequential)]struct Hdr{public IntPtr data;public uint len,recorded;public IntPtr user;public uint flags,loops;public IntPtr next,reserved;}
    [DllImport("winmm.dll")]static extern uint waveInOpen(out IntPtr h,int id,ref Fmt f,IntPtr cb,IntPtr ins,uint fl);[DllImport("winmm.dll")]static extern uint waveInPrepareHeader(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveInAddBuffer(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveInStart(IntPtr h);[DllImport("winmm.dll")]static extern uint waveInReset(IntPtr h);[DllImport("winmm.dll")]static extern uint waveInUnprepareHeader(IntPtr h,IntPtr p,uint s);[DllImport("winmm.dll")]static extern uint waveInClose(IntPtr h);
    [DllImport("winmm.dll")]static extern uint waveInGetNumDevs();[DllImport("winmm.dll",CharSet=CharSet.Auto)]static extern uint waveInGetDevCaps(UIntPtr id,out Caps caps,uint size);
}
